# B as in Bald 2017

# Portfolio collection
collections:
  tests:
    output: false
  portfolio:
    output: true
    permalink: /portfolio/:path/
    title: portfolio
defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Site settings
title: "Bumhan Yu, aka B as in Bald"
email: bumhan.yu@gmail.com
description: Bumhan Yu is a developer/designer, based in New York City.
baseurl: ""
url: ""


include: ["_pages"]
permalink: /blog/:title/


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
future: true

# Pagination settings
gems:
  [jekyll-paginate]
paginate: 7
paginate_path: "/blog/page:num/"
